#!/usr/bin/with-contenv bash

# fix for linting
declare config

# Set version
PHOTOSHOW_COMMIT=$(cat /version.txt)

# install photoshow
if [ ! -d "/config/www/PhotoShow/.git" ]; then
	echo "fetching photoshow files from github"
	git clone https://github.com/Kangaroux/PhotoShow.git /config/www/PhotoShow
	sed -i \
		-e "s#$config->photos_dir.*#$config->photos_dir = \"/Pictures\";#g" \
		-e "s#$config->ps_generated.*#$config->ps_generated  = \"/Thumbs\";#g" \
		-e "s#.*config->timezone.*#\$config->timezone = \"${TZ}\";#g" \
	/config/www/PhotoShow/config.php
fi

# permissions
chown -R abc:abc \
	/config/www/PhotoShow \
	/Thumbs
